### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by isaacabraham** [CompositionalIT/MultiSelect#3]
@Akash-Mair can you get the code you used to build the demo branch? There's just the HTML assets in there, and it would be useful to actually have that F# code in the repo.

**Comment by mattgallagher92** [comment]
@isaacabraham what do you mean by the demo branch? The source F# code for the demo app at https://compositionalit.github.io/MultiSelect/ is in the demo subdirectory of the repo. I'm making some changes which will include improving the documentation, to hopefully make this clearer.
